/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../common";
import type {
  ImplementationEIP1967Three,
  ImplementationEIP1967ThreeInterface,
} from "../../../../proxy-patterns/eip1967_upgradable_proxy/implementation_three.sol/ImplementationEIP1967Three";

const _abi = [
  {
    inputs: [],
    name: "decrement",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "delta",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_input",
        type: "uint256",
      },
    ],
    name: "multiply",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "number",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080604052348015600f57600080fd5b506101648061001f6000396000f3fe608060405234801561001057600080fd5b506004361061004c5760003560e01c806312b495a8146100515780632baeceb71461006c5780638381f58a14610076578063c6888fa11461007f575b600080fd5b61005a60015481565b60405190815260200160405180910390f35b610074610092565b005b61005a60005481565b61005a61008d3660046100cf565b6100a7565b6001546000546100a291906100fe565b600055565b6000816001546000546100ba9190610117565b6100c49190610117565b600081905592915050565b6000602082840312156100e157600080fd5b5035919050565b634e487b7160e01b600052601160045260246000fd5b81810381811115610111576101116100e8565b92915050565b8082028115828204841417610111576101116100e856fea2646970667358221220a3702c292a8932b2099275c6a26d52e47252176d35a15ce0323691c6093b9e9464736f6c634300081a0033";

type ImplementationEIP1967ThreeConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: ImplementationEIP1967ThreeConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class ImplementationEIP1967Three__factory extends ContractFactory {
  constructor(...args: ImplementationEIP1967ThreeConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      ImplementationEIP1967Three & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(
    runner: ContractRunner | null
  ): ImplementationEIP1967Three__factory {
    return super.connect(runner) as ImplementationEIP1967Three__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ImplementationEIP1967ThreeInterface {
    return new Interface(_abi) as ImplementationEIP1967ThreeInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ImplementationEIP1967Three {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as ImplementationEIP1967Three;
  }
}
