/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as eip1967UpgradableProxy from "./eip1967_upgradable_proxy";
export * as minimalProxy from "./minimal-proxy";
