/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface MinimalProxyInterface extends Interface {
  getFunction(nameOrSignature: "clone"): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "Cloned"): EventFragment;

  encodeFunctionData(functionFragment: "clone", values: [AddressLike]): string;

  decodeFunctionResult(functionFragment: "clone", data: BytesLike): Result;
}

export namespace ClonedEvent {
  export type InputTuple = [newAddress: AddressLike];
  export type OutputTuple = [newAddress: string];
  export interface OutputObject {
    newAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MinimalProxy extends BaseContract {
  connect(runner?: ContractRunner | null): MinimalProxy;
  waitForDeployment(): Promise<this>;

  interface: MinimalProxyInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  clone: TypedContractMethod<[target: AddressLike], [string], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "clone"
  ): TypedContractMethod<[target: AddressLike], [string], "nonpayable">;

  getEvent(
    key: "Cloned"
  ): TypedContractEvent<
    ClonedEvent.InputTuple,
    ClonedEvent.OutputTuple,
    ClonedEvent.OutputObject
  >;

  filters: {
    "Cloned(address)": TypedContractEvent<
      ClonedEvent.InputTuple,
      ClonedEvent.OutputTuple,
      ClonedEvent.OutputObject
    >;
    Cloned: TypedContractEvent<
      ClonedEvent.InputTuple,
      ClonedEvent.OutputTuple,
      ClonedEvent.OutputObject
    >;
  };
}
