/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../common";
import type {
  ImplementationEIP1967Two,
  ImplementationEIP1967TwoInterface,
} from "../../../../proxy-patterns/eip1967_upgradable_proxy/implementation_two.sol/ImplementationEIP1967Two";

const _abi = [
  {
    inputs: [],
    name: "decrement",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "increment",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_input",
        type: "uint256",
      },
    ],
    name: "multiply",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "number",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080604052348015600f57600080fd5b5061016f8061001f6000396000f3fe608060405234801561001057600080fd5b506004361061004c5760003560e01c80632baeceb7146100515780638381f58a1461005b578063c6888fa114610076578063d09de08a14610089575b600080fd5b610059610091565b005b61006460005481565b60405190815260200160405180910390f35b6100596100843660046100c7565b6100a5565b6100596100b9565b60016000546100a091906100f6565b600055565b806000546100b3919061010f565b60005550565b6000546100a0906001610126565b6000602082840312156100d957600080fd5b5035919050565b634e487b7160e01b600052601160045260246000fd5b81810381811115610109576101096100e0565b92915050565b8082028115828204841417610109576101096100e0565b80820180821115610109576101096100e056fea26469706673582212201ba7172805ed90de92fa16fa3aa73e4fc7f32e70dd883f8f3ef1c8b00e87e5ed64736f6c634300081a0033";

type ImplementationEIP1967TwoConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: ImplementationEIP1967TwoConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class ImplementationEIP1967Two__factory extends ContractFactory {
  constructor(...args: ImplementationEIP1967TwoConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      ImplementationEIP1967Two & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(
    runner: ContractRunner | null
  ): ImplementationEIP1967Two__factory {
    return super.connect(runner) as ImplementationEIP1967Two__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ImplementationEIP1967TwoInterface {
    return new Interface(_abi) as ImplementationEIP1967TwoInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ImplementationEIP1967Two {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as ImplementationEIP1967Two;
  }
}
