/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as _009CallingParentContractsSol from "./009_calling_parent_contracts.sol";
export type { _009CallingParentContractsSol };
