/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../common";
import type {
  UsingSafeMathExternal,
  UsingSafeMathExternalInterface,
} from "../../007_using_safe_math_external.sol/UsingSafeMathExternal";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "a",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "b",
        type: "uint256",
      },
    ],
    name: "doAddition",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "a",
        type: "uint256",
      },
    ],
    name: "doIdentity",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "a",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "b",
        type: "uint256",
      },
    ],
    name: "doSubtraction",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080604052348015600f57600080fd5b506102bd8061001f6000396000f3fe608060405234801561001057600080fd5b50600436106100415760003560e01c806307008aa2146100465780638cbc6ba61461006b5780639638c4aa1461007e575b600080fd5b6100596100543660046101f7565b610091565b60405190815260200160405180910390f35b610059610079366004610210565b61010e565b61005961008c366004610210565b610121565b60405163ac37eebb60e01b81526004810182905260009073__$067a3d5dc7e47c4abd10d2310bdcdecc50$__9063ac37eebb90602401602060405180830381865af41580156100e4573d6000803e3d6000fd5b505050506040513d601f19601f820116820180604052508101906101089190610232565b92915050565b600061011a838361012d565b9392505050565b600061011a8383610198565b6000828211156101845760405162461bcd60e51b815260206004820152601e60248201527f536166654d6174683a207375627472616374696f6e206f766572666c6f77000060448201526064015b60405180910390fd5b60006101908385610261565b949350505050565b6000806101a58385610274565b90508381101561011a5760405162461bcd60e51b815260206004820152601b60248201527f536166654d6174683a206164646974696f6e206f766572666c6f770000000000604482015260640161017b565b60006020828403121561020957600080fd5b5035919050565b6000806040838503121561022357600080fd5b50508035926020909101359150565b60006020828403121561024457600080fd5b5051919050565b634e487b7160e01b600052601160045260246000fd5b818103818111156101085761010861024b565b808201808211156101085761010861024b56fea26469706673582212201416259c546e53a586504f64aff697cd83503e5080e92719150ff492d943c9fd64736f6c634300081a0033";

type UsingSafeMathExternalConstructorParams =
  | [
      linkLibraryAddresses: UsingSafeMathExternalLibraryAddresses,
      signer?: Signer
    ]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: UsingSafeMathExternalConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => {
  return (
    typeof xs[0] === "string" ||
    (Array.isArray as (arg: any) => arg is readonly any[])(xs[0]) ||
    "_isInterface" in xs[0]
  );
};

export class UsingSafeMathExternal__factory extends ContractFactory {
  constructor(...args: UsingSafeMathExternalConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      const [linkLibraryAddresses, signer] = args;
      super(
        _abi,
        UsingSafeMathExternal__factory.linkBytecode(linkLibraryAddresses),
        signer
      );
    }
  }

  static linkBytecode(
    linkLibraryAddresses: UsingSafeMathExternalLibraryAddresses
  ): string {
    let linkedBytecode = _bytecode;

    linkedBytecode = linkedBytecode.replace(
      new RegExp("__\\$067a3d5dc7e47c4abd10d2310bdcdecc50\\$__", "g"),
      linkLibraryAddresses[
        "contracts/library/my_external_safe_math.sol:MyExternalSafeMath"
      ]
        .replace(/^0x/, "")
        .toLowerCase()
    );

    return linkedBytecode;
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      UsingSafeMathExternal & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(
    runner: ContractRunner | null
  ): UsingSafeMathExternal__factory {
    return super.connect(runner) as UsingSafeMathExternal__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): UsingSafeMathExternalInterface {
    return new Interface(_abi) as UsingSafeMathExternalInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): UsingSafeMathExternal {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as UsingSafeMathExternal;
  }
}

export interface UsingSafeMathExternalLibraryAddresses {
  ["contracts/library/my_external_safe_math.sol:MyExternalSafeMath"]: string;
}
