/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface UserDefinedValueTypesExamplesInterface extends Interface {
  getFunction(
    nameOrSignature: "example_no_uvdt" | "example_uvdt"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "example_no_uvdt",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "example_uvdt",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "example_no_uvdt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "example_uvdt",
    data: BytesLike
  ): Result;
}

export interface UserDefinedValueTypesExamples extends BaseContract {
  connect(runner?: ContractRunner | null): UserDefinedValueTypesExamples;
  waitForDeployment(): Promise<this>;

  interface: UserDefinedValueTypesExamplesInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  example_no_uvdt: TypedContractMethod<[], [bigint], "view">;

  example_uvdt: TypedContractMethod<[], [void], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "example_no_uvdt"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "example_uvdt"
  ): TypedContractMethod<[], [void], "view">;

  filters: {};
}
