/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  C,
  CInterface,
} from "../../../inheritence/009_calling_parent_contracts.sol/C";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "string",
        name: "message",
        type: "string",
      },
    ],
    name: "Log",
    type: "event",
  },
  {
    inputs: [],
    name: "bar",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "foo",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080604052348015600f57600080fd5b506101bf8061001f6000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c8063c29855781461003b578063febb0f7e14610045575b600080fd5b61004361004d565b005b61004361009b565b60008051602061016a833981519152604051610089906020808252600c908201526b10cb999bdbc818d85b1b195960a21b604082015260600190565b60405180910390a16100996100e7565b565b60008051602061016a8339815191526040516100d7906020808252600c908201526b10cb98985c8818d85b1b195960a21b604082015260600190565b60405180910390a161009961012d565b60008051602061016a833981519152604051610123906020808252600c908201526b104b999bdbc818d85b1b195960a21b604082015260600190565b60405180910390a1565b60008051602061016a833981519152604051610123906020808252600c908201526b104b98985c8818d85b1b195960a21b60408201526060019056fecf34ef537ac33ee1ac626ca1587a0a7e8e51561e5514f8cb36afa1c5102b3baba2646970667358221220c19d0eaf60999089f4c7f19ce5e4805e68d7fb63c28bcbbb7c6938020948091d64736f6c634300081a0033";

type CConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: CConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class C__factory extends ContractFactory {
  constructor(...args: CConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      C & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): C__factory {
    return super.connect(runner) as C__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): CInterface {
    return new Interface(_abi) as CInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): C {
    return new Contract(address, _abi, runner) as unknown as C;
  }
}
