/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  D,
  DInterface,
} from "../../../inheritence/009_calling_parent_contracts.sol/D";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "string",
        name: "message",
        type: "string",
      },
    ],
    name: "Log",
    type: "event",
  },
  {
    inputs: [],
    name: "bar",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "foo",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080604052348015600f57600080fd5b506102168061001f6000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c8063c29855781461003b578063febb0f7e14610045575b600080fd5b61004361004d565b005b610043610057565b61005561005f565b565b6100556100ab565b6000805160206101c183398151915260405161009b906020808252600c908201526b10cb999bdbc818d85b1b195960a21b604082015260600190565b60405180910390a16100556100f7565b6000805160206101c18339815191526040516100e7906020808252600c908201526b10cb98985c8818d85b1b195960a21b604082015260600190565b60405180910390a161005561013d565b6000805160206101c1833981519152604051610133906020808252600c908201526b104b999bdbc818d85b1b195960a21b604082015260600190565b60405180910390a1565b6000805160206101c1833981519152604051610179906020808252600c908201526b108b98985c8818d85b1b195960a21b604082015260600190565b60405180910390a16100556000805160206101c1833981519152604051610133906020808252600c908201526b104b98985c8818d85b1b195960a21b60408201526060019056fecf34ef537ac33ee1ac626ca1587a0a7e8e51561e5514f8cb36afa1c5102b3baba26469706673582212207d93ea21fd208d3ae57302bff6cd9931ce6ffaf56167e465a26f97c82c3e2c6e64736f6c634300081a0033";

type DConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: DConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class D__factory extends ContractFactory {
  constructor(...args: DConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      D & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): D__factory {
    return super.connect(runner) as D__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): DInterface {
    return new Interface(_abi) as DInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): D {
    return new Contract(address, _abi, runner) as unknown as D;
  }
}
