/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as cloneFactorySol from "./CloneFactory.sol";
export type { cloneFactorySol };
import type * as counterOneSol from "./CounterOne.sol";
export type { counterOneSol };
export type { MinimalProxyOne } from "./MinimalProxyOne";
