/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../common";
import type {
  ImplementationEIP1967One,
  ImplementationEIP1967OneInterface,
} from "../../../../proxy-patterns/eip1967_upgradable_proxy/implementation.sol/ImplementationEIP1967One";

const _abi = [
  {
    inputs: [],
    name: "increment",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "number",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080604052348015600f57600080fd5b5060c680601d6000396000f3fe6080604052348015600f57600080fd5b506004361060325760003560e01c80638381f58a146037578063d09de08a146051575b600080fd5b603f60005481565b60405190815260200160405180910390f35b60576059565b005b6000546065906001606a565b600055565b80820180821115608a57634e487b7160e01b600052601160045260246000fd5b9291505056fea264697066735822122025a84e03925404d5931ccc78b2b3729e3b7e25ac66b11e34c918d1f8de65ef5e64736f6c634300081a0033";

type ImplementationEIP1967OneConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: ImplementationEIP1967OneConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class ImplementationEIP1967One__factory extends ContractFactory {
  constructor(...args: ImplementationEIP1967OneConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      ImplementationEIP1967One & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(
    runner: ContractRunner | null
  ): ImplementationEIP1967One__factory {
    return super.connect(runner) as ImplementationEIP1967One__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ImplementationEIP1967OneInterface {
    return new Interface(_abi) as ImplementationEIP1967OneInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ImplementationEIP1967One {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as ImplementationEIP1967One;
  }
}
