/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../common";
import type {
  UserDefinedValueTypesExamples,
  UserDefinedValueTypesExamplesInterface,
} from "../../005_userdefined_value_types.sol/UserDefinedValueTypesExamples";

const _abi = [
  {
    inputs: [],
    name: "example_no_uvdt",
    outputs: [
      {
        internalType: "Clock",
        name: "",
        type: "uint128",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "example_uvdt",
    outputs: [],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080604052348015600f57600080fd5b50609b80601d6000396000f3fe6080604052348015600f57600080fd5b506004361060325760003560e01c8063645e9edf1460375780639848d8e6146063575b600080fd5b60014260401b176040516fffffffffffffffffffffffffffffffff909116815260200160405180910390f35b00fea2646970667358221220037593fe609495d892c8c4c37006061644de87208c92c7b726973a237b1eeca264736f6c634300081a0033";

type UserDefinedValueTypesExamplesConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: UserDefinedValueTypesExamplesConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class UserDefinedValueTypesExamples__factory extends ContractFactory {
  constructor(...args: UserDefinedValueTypesExamplesConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      UserDefinedValueTypesExamples & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(
    runner: ContractRunner | null
  ): UserDefinedValueTypesExamples__factory {
    return super.connect(runner) as UserDefinedValueTypesExamples__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): UserDefinedValueTypesExamplesInterface {
    return new Interface(_abi) as UserDefinedValueTypesExamplesInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): UserDefinedValueTypesExamples {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as UserDefinedValueTypesExamples;
  }
}
