/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as eip1967UpgradableProxy from "./eip1967_upgradable_proxy";
export type { eip1967UpgradableProxy };
import type * as minimalProxy from "./minimal-proxy";
export type { minimalProxy };
