/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as implementationSol from "./implementation.sol";
export type { implementationSol };
import type * as implementationThreeSol from "./implementation_three.sol";
export type { implementationThreeSol };
import type * as implementationTwoSol from "./implementation_two.sol";
export type { implementationTwoSol };
export type { BuggyProxy } from "./BuggyProxy";
export type { SimpleProxy } from "./SimpleProxy";
